id: A16245EEF
base_file: f19B0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:54:19.492839
  last_modified_at: 2022-05-30 18:54:19.492865
