id: A16245EEF
base_file: f127F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:54:19.490105
  last_modified_at: 2022-05-30 18:54:19.490113
