id: A16245EEF
base_file: f7B2C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:54:19.494637
  last_modified_at: 2022-05-30 18:54:19.494644
