id: A16245EEF
base_file: f9BF9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:54:19.496992
  last_modified_at: 2022-05-30 18:54:19.496999
